//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.1.
//


package com.drjane.promise.ui.fragment;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;
import com.drjane.promise.model.Order;
import org.androidannotations.api.builder.FragmentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class OrderDetailFragment_
    extends com.drjane.promise.ui.fragment.OrderDetailFragment
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private View contentView_;
    public final static String M_ORDER_ARG = "order";

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    @Override
    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        return contentView_;
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        injectFragmentArguments_();
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static OrderDetailFragment_.FragmentBuilder_ builder() {
        return new OrderDetailFragment_.FragmentBuilder_();
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        mRemarksTv = ((TextView) hasViews.findViewById(com.drjane.promise.R.id.tv_remarks));
        mDateTv = ((TextView) hasViews.findViewById(com.drjane.promise.R.id.tv_shootingDate));
        mMMId = ((TextView) hasViews.findViewById(com.drjane.promise.R.id.tv_mmId));
        mLocationTv = ((TextView) hasViews.findViewById(com.drjane.promise.R.id.tv_shootingLocation));
        mNameTv = ((TextView) hasViews.findViewById(com.drjane.promise.R.id.tv_costmerName));
        mPhoneTv = ((TextView) hasViews.findViewById(com.drjane.promise.R.id.tv_phone));
        mOrderPackegeTv = ((TextView) hasViews.findViewById(com.drjane.promise.R.id.tv_orderPackege));
        init();
    }

    private void injectFragmentArguments_() {
        Bundle args_ = getArguments();
        if (args_!= null) {
            if (args_.containsKey(M_ORDER_ARG)) {
                mOrder = ((Order) args_.getSerializable(M_ORDER_ARG));
            }
        }
    }

    public static class FragmentBuilder_
        extends FragmentBuilder<OrderDetailFragment_.FragmentBuilder_, com.drjane.promise.ui.fragment.OrderDetailFragment>
    {


        @Override
        public com.drjane.promise.ui.fragment.OrderDetailFragment build() {
            OrderDetailFragment_ fragment_ = new OrderDetailFragment_();
            fragment_.setArguments(args);
            return fragment_;
        }

        public OrderDetailFragment_.FragmentBuilder_ mOrder(Order mOrder) {
            args.putSerializable(M_ORDER_ARG, mOrder);
            return this;
        }

    }

}
